INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Uniform', 93.8300, 21, 798, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo Zulu', 50.1700, 6, 486, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Kilo', 20.5200, 7, 664, 1);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Golf', 78.8900, 1, 622, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu November', 61.8600, 43, 296, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Golf', 63.2800, 33, 130, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Echo Alfa', 48.2900, 9, 548, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Alfa Papa', 47.6100, 45, 445, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Alfa', 82.4100, 12, 80, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Charlie Yankee', 29.5000, 7, 585, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Alfa Quebec', 53.5700, 49, 640, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo', 82.8300, 9, 288, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Whiskey Mike', 63.5600, 38, 976, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Sierra Papa', 57.3000, 11, 926, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec Shrek', 37.0100, 32, 500, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo', 85.1400, 14, 366, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Oscar Sierra', 53.6200, 26, 234, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Golf Romeo', 43.3100, 36, 168, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango Juliett', 39.5400, 27, 192, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu November', 10.1400, 7, 291, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec', 55.7100, 42, 102, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'India Romeo', 64.4500, 37, 999, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec Bravo', 88.0200, 49, 731, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Kilo Golf', 58.6200, 1, 621, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Foxtrot India', 55.8400, 24, 127, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Delta Mike', 58.9700, 34, 270, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Mike Golf', 97.8200, 23, 139, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Yankee', 15.3000, 46, 984, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Juliett Charlie', 88.5200, 43, 453, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Mike Echo', 82.3700, 19, 488, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango Alfa', 48.9200, 30, 285, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu', 91.9500, 43, 417, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo Yankee', 21.6300, 46, 579, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'November', 49.8900, 40, 921, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec Oscar', 97.1700, 42, 97, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Papa', 23.0500, 15, 144, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec Oscar', 80.3400, 39, 278, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Oscar', 50.1900, 35, 950, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo Charlie', 48.2300, 7, 182, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Sierra Victor', 60.5600, 46, 487, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Whiskey', 77.5300, 39, 828, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Papa', 41.7500, 45, 254, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec', 98.5700, 37, 287, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo Victor', 62.0900, 18, 886, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Delta', 33.7600, 19, 39, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Whiskey Echo', 31.3500, 8, 171, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo', 98.4400, 4, 286, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Kilo', 40.3200, 49, 484, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Kilo', 17.5800, 20, 402, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'India Tango', 88.9300, 33, 524, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Charlie', 10.3200, 46, 786, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Mike Alfa', 90.1800, 25, 338, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Hotel Lima', 77.5400, 38, 899, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu Alfa', 75.9900, 1, 44, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'X-ray', 75.4800, 44, 785, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango', 91.5200, 40, 964, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo Oscar', 31.9700, 10, 362, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Mike India', 57.8100, 42, 76, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Yankee Lima', 65.1400, 2, 188, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu', 76.2100, 9, 345, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Uniform Delta', 85.0400, 32, 952, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Charlie', 26.2900, 29, 430, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango', 63.4700, 31, 733, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Hotel', 13.8000, 42, 691, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo', 47.1000, 16, 311, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Yankee', 58.3300, 46, 105, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'X-ray', 65.1300, 35, 618, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'India', 85.7000, 36, 707, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Oscar November', 25.4200, 45, 992, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'X-ray Tango', 65.2700, 34, 775, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Delta', 66.7300, 29, 192, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango', 71.3100, 28, 507, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Hotel Alfa', 27.8600, 28, 648, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo', 86.3000, 24, 907, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Foxtrot', 17.0100, 30, 722, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Sierra Romeo', 36.1800, 43, 490, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Lima Charlie', 93.0600, 13, 247, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Victor', 62.4200, 24, 890, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Oscar Whiskey', 77.3200, 4, 235, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Yankee November', 89.6000, 8, 717, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Juliett', 27.4600, 43, 315, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Quebec Tango', 88.8100, 14, 204, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Echo', 81.6300, 18, 176, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Lima', 93.4000, 1, 78, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Whiskey', 84.2300, 18, 387, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Papa Golf', 76.5600, 21, 982, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Papa', 37.7000, 33, 803, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'India', 83.4800, 45, 249, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Victor Bravo', 80.3200, 10, 100, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Zulu', 29.2100, 13, 182, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'X-ray Delta', 20.5200, 22, 773, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Mike', 29.1100, 14, 304, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Yankee', 38.8100, 14, 473, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Bravo X-ray', 65.9200, 30, 670, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'November', 99.4300, 16, 150, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Tango India', 61.1800, 50, 590, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'India Hotel', 77.0300, 18, 327, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Lima Romeo', 56.8800, 11, 426, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Romeo Uniform', 17.4400, 45, 270, 0);
INSERT INTO GoFlex.dbo.EventPrice (Name, Price, EventId, Total, IsRemoved) VALUES (N'Charlie Zulu', 64.6600, 22, 267, 0);