on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: goflex
  AZURE_WEBAPP_PACKAGE_PATH: ./goflex
  GITHUB_REPO_LINK: https://github.com/shepshook/go-flex/
  DOTNET_VERSION: 3.1.301

jobs:

  build-test-deploy:
    
    name: Build, test and deploy to Azure
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      id: publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
    - name: Deploy to Azure WebApp
      id: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
